# -*- coding: utf-8 -*-
"""Append a consolidated FIGURE LEGENDS section to the figure-embedded manuscript,
output as manuscript_full_with_figures_v4.md. Numbers are taken verbatim from the
verified milestone outputs (no fabrication)."""

SRC = "E:/Workbuddy/2026-07-27-11-58-27/manuscript/manuscript_full_with_figures.md"
OUT = "E:/Workbuddy/2026-07-27-11-58-27/manuscript/manuscript_full_with_figures_v6.md"

LEGENDS = r"""# FIGURE LEGENDS

## Figure 1. A Harmony-batch-corrected single-cell reference atlas of porcine preimplantation embryogenesis.
(A) UMAP embedding of the integrated atlas (n = 1,955 high-quality cells after QC, 1% removed) coloured by developmental stage, spanning the germinal-vesicle (GV) oocyte through embryonic day E14 and *in vitro*-derived pregastrulation epiblast stem cells (pgEpiSCs). PCA (50 dimensions; top-5 PCs explain 45% of variance) followed by **Harmony** batch correction [10] and UMAP preserves the full oocyte→post-implantation trajectory. (B) The same embedding coloured by reproductive source (IVF / PA / *in vivo* / GV). Cells from the same developmental window co-cluster across independent studies (e.g., GSE168106 E-series with GSE112380 preimplantation samples), demonstrating that developmental stage — not batch — is the dominant axis of variation. (C–E) Batch-removal diagnostics. The embedded comparison panel shows that Harmony reduced the embedding variance attributable to dataset from 7.7% to 2.1%, while the variance attributable to developmental stage remained dominant (18.3% → 15.5%), raising the stage:batch signal ratio from 2.4 (PCA centring) to 7.4. A dataset-contribution sankey (reported in the body text) confirmed balanced cross-donor representation.

## Figure 2. Parthenogenetic embryos diverge most from the *in vivo* trajectory.
(A–B) Cross-condition pseudotime divergence. PCA-derived pseudotime was aligned per condition and per-gene deviation computed across 8,276 analysable genes. Among the 50 most divergent genes, mean divergence was IVF_vs_PA = 0.90, IVF_vs_vivo = 2.74, and PA_vs_vivo = 3.24; for 42/50 genes the largest deviation was PA-vs-vivo, 8/50 IVF-vs-vivo, and 0/50 IVF-vs-PA. Genome-wide, 82.9% of genes showed PA_vs_vivo > IVF_vs_PA. Top divergent genes include KLHL15 and the mitochondrial OXPHOS subunits ATP6 (MT-ATP6) and ND5 (MT-ND5). (C) IVF vs PA differential expression (GSE164812; IVF n = 21, PA n = 21 cells). Wilcoxon rank-sum on FPKM with Benjamini–Hochberg correction identified 186 significant genes (|log₂FC| > 0.5), of which 104 were down- and 15 up-regulated in PA. (D) Reactome enrichment of the 104 PA-down genes, highlighting Rho GTPase signalling, mitotic centromere/kinetochore, and SUMOylation (top adj-p = 0.115; raw p: SUMOylation 0.012, Rho GTPases 0.009–0.026). (E) Imprint-locus overlap test. None of the 104 PA-down genes overlapped paternally- or maternally-expressed imprint loci (Fisher's exact p = 1.0), indicating the PA deficit is a broad competence/execution failure rather than selective loss of paternal imprints.

## Figure 3. Pseudobulk differential expression along the preimplantation trajectory.
(A) Volcano plot of Early (E0–E3) vs Late (E11–E14) pseudobulk DESeq2 (pydeseq2) on GSE168106, aggregating cells per embryonic day as the replication unit (n = 4 per group). Of 24,948 genes tested, 11,621 were significant (padj < 0.05, |log₂FC| > 1), comprising 5,677 up- and 5,944 down-regulated in the late group. (B) MA plot of the same contrast; large effect sizes (many |log₂FC| > 9) span roughly half the transcriptome, so the developmental signal is robust despite modest n.

## Figure 4. Multi-omics re-analysis of porcine GV oocyte maturation states.
Multi-omics overview of GSE234116 (Yuan *et al.*, 2023) re-analysis. Unsupervised PCA + k-means on single-cell M&T-seq RNA recovered two oocyte states (our call: n = 32 Type I / n = 23 Type II), direction-consistent with the original report (n = 25 / n = 29). Type II oocytes carried ~1.4× the cytoplasmic transcript load of Type I (mean transcripts 15.7 M vs 10.9 M). Type II vs Type I yielded 12,664 significantly up-regulated genes and only 3 down-regulated, enriched in meiosis, HIF-1, Ras, mTOR, ErbB and PI3K–Akt pathways. Differentially methylated regions (DMRs) are referenced from the original study: 1,141 DMRs, of which 1,140 (99.91%) are hypermethylated in Type II, enriched in PI3K–Akt/mTOR/cell-growth programmes, with higher DNMT1/3A/3B expression in Type II.

## Figure 5. Gene regulatory network inference identifies ZGA-associated and lineage regulators.
(A–B) pySCENIC regulon heatmap (46 motif-validated regulons × 1,833 cells, ordered by stage) and AUCell activity. GRNBoost2 co-expression across 246 porcine TFs × 3,000 HVGs produced 304,706 TF–target links, pruned by cisTarget motif enrichment to 46 regulons (261 TF± modules; target sizes 7–2,727, mean 323). (C) Stage-resolved mean AUC for key regulons: ESRRA activity is highest at the zygote–cleavage window (E0–E3 AUC ≈ 0.18–0.22) and declines toward blastocyst; MXD3 (a MYC antagonist) is near-zero early and rises at blastocyst (E6–E14 ≈ 0.11–0.13); POU5F1 (OCT4) and TFAP2C peak in *in vitro* and GV compartments; GATA4, BACH1, ATF3 peak at E8–E9. The top regulons by mean AUC — ESRRA(+), ATF7(+), MXD3(+), ATF3(+), TFAP2C(+), POU5F1/OCT4(+), EGR1(+), MYC(+), GATA4(+), BACH1(+) — recapitulate the Oct4/TFAP2C pluripotency–trophoblast axis, the ESRRA oxidative-metabolism programme, and the ATF3/ATF7/BACH1 stress–antioxidant axis. (D) Key TF regulon activity trajectories across development. (E) Lineage-level regulon specificity. GSE168106 cells at E6–E14 (n = 1,117) were re-clustered by K-means (K = 4) on the Harmony 50-D embedding; clusters were annotated using canonical markers (POU5F1/NANOG/SOX2 → ICM; CDX2/GATA3/KRT8/KRT18 → TE; GATA4/GATA6/SOX17/PDGFRA → PrE). Panel A shows the cluster × marker z-score matrix; panel B shows mean AUC of the top lineage-specific regulons. PrE showed strong enrichment of XBP1(+) (FC = 4.55), GATA2(+) (FC = 3.01), CEBPG(+) (FC = 2.70), ATF3(+) (FC = 2.57), CHURC1(+) (FC = 2.28), BACH1(+) (FC = 2.25); the ICM/TE-mixed cluster showed enrichment of NFE2L3(+) (FC = 2.85) and POU5F1(+) (FC = 1.71). Specificity score = mean AUC in most-enriched lineage / mean AUC across other lineages. (F) Core TF regulatory network. Co-expression edges from GRNBoost2 for six core TFs (ESRRA, POU5F1, MXD3, GATA4, PAX6, TFAP2C), each with its top-20 highest-weight targets (120 edges total). Network illustrates target breadth per TF and provides a tractable entry point for downstream enhancer-driven validation. SCENIC+ enhancer-driven enhancer-gene regulatory networks require paired scRNA + scATAC data, which are absent from every dataset in this atlas; therefore the analysis is RNA-only pySCENIC.

## Figure 6. Metabolic module scoring reveals an OxPhos-dominant preimplantation programme.
Glycolysis and OxPhos module scores (genes ortholog-mapped to human KEGG; AUCell) across the preimplantation time course (GSE168106, n = 4–174 cells/stage) and across conditions (IVF vs PA, n = 21 each). The glycolysis/OxPhos ratio remained < 0.6 at every stage (mean 0.437; range 0.315 at E5 to 0.563 at E2), with a mid-cleavage trough (E4–E7 ≈ 0.32–0.35) and a gradual rise toward blastocyst (E14 = 0.54). Both IVF and PA were OxPhos-dominant (IVF ratio 0.649; PA ratio 0.654); PA showed slightly lower absolute OxPhos activity (0.292 vs 0.351). The ratio staying OxPhos-dominant through E14 is consistent with the conserved late-blastocyst "bivalent respiration" state (Malkowska *et al.*, 2022); the gastrulation-phase glycolytic switch lies beyond the present dataset.

## Figure 7. Waddington-OT lineage reconstruction resolves fate plasticity and cross-condition developmental displacement.
(A) UMAP of the *in vivo* GSE168106 backbone (E0–E8) coloured by Waddington-OT fate entropy (nats). Early cells (E0–E2, yellow) show near-maximal entropy (≈0.99 nats; theoretical maximum for K = 3 fates = log(3) ≈ 1.10), reflecting broad developmental potential; terminal E8 cells (purple) show entropy ≈0, reflecting commitment. (B) Mean fate entropy (green, left axis) decreases and mean maximum terminal-fate probability (red, right axis) increases across development; entropy reaches 0 at E8 as commitment becomes deterministic. (C) Per-stage latent-space displacement of IVF and PA cells (GSE164812, 1C–8C mapped to matched *in vivo* stages 1C→E2 … 8C→E5) from the *in vivo* reference. Boxplots show both *in vitro* origins are shifted from the physiological trajectory, with PA deviating most strongly in several matched windows; overall mean displacement across E2–E5 was in-vivo self-reference 8.33 ± 2.64, IVF 10.24 ± 1.95, and PA 10.15 ± 1.51 standardised HPC units. (D) UMAP coloured by maximum probability toward a terminal E8 fate; commitment is spatially organised, with multipotent cells at the early-cleavage end (yellow) and concentrated fate probability in the blastocyst/post-implantation branches (purple).

## Figure 8. MOFA+ decomposes multi-study gene-expression variance into interpretable developmental axes.
MOFA+ was run on 3,000 highly variable genes across 1,833 cells from three studies (GSE168106 *in vivo* E0–E14, GSE112380 *in vitro*, GSE234116 GV oocytes), using group centering to remove study-mean offsets. (A) Variance explained by each of ten latent factors; the full model explains 21.6% of total variance, with F1 alone accounting for 11.6%. (B) Trajectories of the three factors most strongly correlated with canonical developmental stage (GV → E14). F2 (oocyte/MZT programme; r = −0.68) peaks in the early stages, while F3 and F8 show later modulation. (C) Top loading genes on the dominant F1 axis, comprising cell-cycle and proliferation regulators (CCNB2, CDKN3, HAUS1, KIF23, SGO1, CDC27, VRK1). (D) Heatmap of top gene loadings across the three most stage-correlated factors; each factor is driven by a distinct gene set, confirming that the integrated atlas retains biologically meaningful, shared axes of variation after Harmony correction.
"""

with open(SRC, encoding="utf-8") as f:
    body = f.read().rstrip("\n")

# Append a separator and the legends block.
out_text = body + "\n\n" + LEGENDS

with open(OUT, "w", encoding="utf-8") as f:
    f.write(out_text)

print("Wrote", OUT, "| total chars:", len(out_text))
