#!/usr/bin/env python3
"""
M7 upgrade (part 1): GRNBoost2 co-expression regulons + AUCell activity.
Does NOT require the cisTarget ranking DB (feather). Produces regulatory
activity along developmental stages for Fig.5.
Input : m7_expr_human_symbol.csv  (human symbols x cells, from wsl_prepare_human_map.py)
Output: pyscenic_out/adj.csv, pyscenic_out/regulons_coexpr.csv,
        pyscenic_out/aucell_scores.csv, and Fig.5 panels.

If the full pySCENIC ctx (motif-enriched) regulons become available later,
this script's AUCell step can be re-run on those regulons for the upgrade.
"""
import pandas as pd
import numpy as np
import os
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

BASE = '/mnt/e/Workbuddy/2026-07-27-11-58-27'
PROC = f'{BASE}/data/processed'
OUT = f'{PROC}/pyscenic_out'
os.makedirs(OUT, exist_ok=True)

# Load HVG symbol expression matrix (pig symbols x cells, from wsl_prepare_symbol_map.py)
expr = pd.read_csv(f'{PROC}/m7_hvg_symbol.csv', index_col=0)
print(f"Expression matrix (HVG): {expr.shape[0]} genes x {expr.shape[1]} cells")

# Load metadata (cells mapped to dataset)
meta = pd.read_csv(f'{PROC}/m7_cells_metadata.csv', index_col=0)
meta = meta.loc[[c for c in expr.columns if c in meta.index]]
# Stage info comes from sample info; assign simple stage groups per dataset
stage_map = {
    'GSE168106': 'in_vivo_embryo',
    'GSE112380': 'in_vivo_preimpl',
    'GSE234116': 'GV_oocyte',
}
meta['stage_group'] = meta['dataset'].map(stage_map).fillna('unknown')

# ---------------------------------------------------------------
# Step 1: Load GRN links (generated by `pyscenic grn` CLI)
# ---------------------------------------------------------------
adj_path = f'{OUT}/adj.csv'
if not os.path.exists(adj_path):
    raise FileNotFoundError(f"{adj_path} not found. Run: pyscenic grn m7_hvg_symbol.csv -o {adj_path} -p 8")
print(f"Loading GRN links from {adj_path}...")
adj = pd.read_csv(adj_path)
print(f"GRN links: {len(adj)}")

# ---------------------------------------------------------------
# Step 2: Build co-expression regulons (TF + top targets)
# ---------------------------------------------------------------
print("Building co-expression regulons...")
# Keep top targets per TF by importance
topn = 50
regulons = {}
for tf, grp in adj.groupby('TF'):
    grp = grp.sort_values('importance', ascending=False).head(topn)
    regulons[tf] = list(grp['target'])
reg_df = pd.DataFrame([{'TF': tf, 'n_targets': len(t),
                        'targets': ','.join(t)} for tf, t in regulons.items()])
reg_df.to_csv(f'{OUT}/regulons_coexpr.csv', index=False)
print(f"Regulons (TFs): {len(regulons)}")

# ---------------------------------------------------------------
# Step 3: AUCell (rank-based AUC per regulon)
# ---------------------------------------------------------------
print("Computing AUCell activity...")
# For each cell, rank genes by expression; AUC = area under recovery curve of target ranks
X = expr.values.astype(np.float32)  # genes x cells
n_genes, n_cells = X.shape
# ranks within each cell (column)
ranks = np.zeros_like(X)
for j in range(n_cells):
    ranks[:, j] = pd.Series(X[:, j]).rank().values
# normalize ranks to [0,1]
ranks_norm = (ranks - 1) / (n_genes - 1)

auc = np.zeros((len(regulons), n_cells))
tf_names = list(regulons.keys())
for i, tf in enumerate(tf_names):
    targets = [t for t in regulons[tf] if t in expr.index]
    if len(targets) < 5:
        auc[i, :] = 0
        continue
    idx = [list(expr.index).index(t) for t in targets]
    # AUC = mean of normalized ranks of targets, scaled by target fraction
    auc[i, :] = ranks_norm[idx, :].mean(axis=0) * (len(targets) / n_genes)

auc_df = pd.DataFrame(auc, index=tf_names, columns=expr.columns)
auc_df.to_csv(f'{OUT}/aucell_scores.csv')
print(f"AUCell matrix: {auc_df.shape}")

# ---------------------------------------------------------------
# Step 4: Visualization (Fig.5 panels)
# ---------------------------------------------------------------
print("Plotting...")
# Panel A: top dynamic regulons (by variance across cells)
row_var = auc_df.var(axis=1).sort_values(ascending=False)
top_tfs = row_var.head(25).index.tolist()
fig, ax = plt.subplots(figsize=(10, 8))
im = ax.imshow(auc_df.loc[top_tfs].values, aspect='auto', cmap='viridis')
ax.set_yticks(range(len(top_tfs)))
ax.set_yticklabels(top_tfs, fontsize=8)
ax.set_xlabel('Cells (ordered)')
ax.set_title('Top 25 most variable regulons (AUCell activity)')
plt.colorbar(im, ax=ax, label='AUCell')
plt.tight_layout()
fig.savefig(f'{OUT}/fig5_regulon_heatmap.png', dpi=150)
plt.close()

# Panel B: mean AUCell per stage group for top TFs
stage_order = ['GV_oocyte', 'in_vivo_preimpl', 'in_vivo_embryo']
mean_by_stage = pd.DataFrame(index=top_tfs)
for sg in stage_order:
    cells = meta.index[meta['stage_group'] == sg]
    cells = [c for c in cells if c in auc_df.columns]
    if cells:
        mean_by_stage[sg] = auc_df.loc[top_tfs, cells].mean(axis=1).values
mean_by_stage = mean_by_stage.fillna(0)
fig, ax = plt.subplots(figsize=(10, 8))
im = ax.imshow(mean_by_stage.values, aspect='auto', cmap='RdBu_r', vmin=-0.02, vmax=0.02)
ax.set_yticks(range(len(top_tfs))); ax.set_yticklabels(top_tfs, fontsize=8)
ax.set_xticks(range(len(stage_order))); ax.set_xticklabels(stage_order, fontsize=10)
ax.set_title('Mean regulon activity by stage group')
plt.colorbar(im, ax=ax, label='AUCell')
plt.tight_layout()
fig.savefig(f'{OUT}/fig5_regulon_by_stage.png', dpi=150)
plt.close()

# Panel C: specific TF regulons of interest (if present)
interesting = [t for t in ['NANOG','POU5F1','SOX2','OCT4','CDX2','TEAD4','GATA3','ELF5'] if t in auc_df.index]
if interesting:
    fig, axes = plt.subplots(1, len(interesting), figsize=(3*len(interesting), 4))
    if len(interesting) == 1:
        axes = [axes]
    for ax, tf in zip(axes, interesting):
        cells_order = auc_df.columns
        ax.scatter(range(len(cells_order)), auc_df.loc[tf, cells_order], s=3)
        ax.set_title(tf); ax.set_xlabel('cells'); ax.set_ylabel('AUCell')
    plt.tight_layout()
    fig.savefig(f'{OUT}/fig5_key_tf_regulons.png', dpi=150)
    plt.close()

print("DONE. Outputs in", OUT)
